INSERT INTO users (name, age) VALUES ("user1", 25);
INSERT INTO users (name, age) VALUES ("user2", 33);
INSERT INTO users (name, age) VALUES ("user3", 55);
INSERT INTO users (name, age) VALUES ("user4", 60);
INSERT INTO users (name, age) VALUES ("user5", 80);
INSERT INTO users (name, age) VALUES ("user6", 65);
INSERT INTO users (name, age) VALUES ("user7", 23);
INSERT INTO users (name, age) VALUES ("user8", 21);
INSERT INTO users (name, age) VALUES ("user9", 18);
INSERT INTO users (name, age) VALUES ("user10", 68);
INSERT INTO users (name, age) VALUES ("user11", 54);
INSERT INTO users (name, age) VALUES ("user12", 73);
INSERT INTO users (name, age) VALUES ("user13", 39);
INSERT INTO users (name, age) VALUES ("user14", 19);
INSERT INTO users (name, age) VALUES ("user15", 55);
INSERT INTO users (name, age) VALUES ("user16", 37);
INSERT INTO users (name, age) VALUES ("user17", 29);
INSERT INTO users (name, age) VALUES ("user18", 39);
INSERT INTO users (name, age) VALUES ("user19", 48);
INSERT INTO users (name, age) VALUES ("user20", 51);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project1', 'music', 100, '2021-05-22', '2021-05-23');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project2', 'music', 100, '2021-06-22', '2021-06-23');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project3', 'music', 100, '2021-07-22', '2021-07-23');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project4', 'music', 100, '2021-08-22', '2021-08-23');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project5', 'music', 100, '2021-09-22', '2021-09-23');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project6', 'music', 100, '2021-10-22', '2021-10-23');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project7', 'music', 100, '2021-11-22', '2021-11-23');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project8', 'music', 100, '2021-12-22', '2021-12-23');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project9', 'music', 100, '2021-04-22', '2021-04-23');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project10', 'music', 100, '2021-03-22', '2021-03-23');

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 5, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 7, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 9, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 5, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 7, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 5, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 9, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 10, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 5, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 2);